---
title: "MED131 - Biostatistics - Fall 2021"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schedule, echo=FALSE}
suppressMessages(sched_df <- readxl::read_excel("misc/MED131_lectures.xlsx"))

sched_df$Slides <- sched_df$`R script` <- NULL
colnames(sched_df)[4] <- "review"
sched_df$review[is.na(sched_df$review)] <- ""
sched_df$review[14] <- "review before final"

# links to lectures
base_url <- "https://github.com/egeulgen/MED131_21_22/blob/main/"
sched_df$Subject[1] <- kableExtra::cell_spec(sched_df$Subject[1], "html", link = paste0(base_url, "lectures/1.descriptive.pdf"))
sched_df$Subject[2] <- kableExtra::cell_spec(sched_df$Subject[2], "html", link = paste0(base_url, "lectures/2.descriptive.pdf"))
sched_df$Subject[3] <- kableExtra::cell_spec(sched_df$Subject[3], "html", link = paste0(base_url, "lectures/3.hypothesis_testing_one_sample.pdf"))
sched_df$Subject[5] <- kableExtra::cell_spec(sched_df$Subject[5], "html", link = paste0(base_url, "lectures/5.two_sample_anova.pdf"))
sched_df$Subject[7] <- kableExtra::cell_spec(sched_df$Subject[7], "html", link = paste0(base_url, "lectures/7.chi_squared.pdf"))
sched_df$Subject[8] <- kableExtra::cell_spec(sched_df$Subject[8], "html", link = paste0(base_url, "lectures/8.nonparametric_linear_reg.pdf"))
sched_df$Subject[9] <- kableExtra::cell_spec(sched_df$Subject[9], "html", link = paste0(base_url, "lectures/9.logistic_poisson.pdf"))
sched_df$Subject[12] <- kableExtra::cell_spec(sched_df$Subject[12], "html", link = paste0(base_url, "lectures/12.sampling_missing.pdf"))
sched_df$Subject[13] <- kableExtra::cell_spec(sched_df$Subject[13], "html", link = paste0(base_url, "lectures/13.power_analysis.pdf"))

kableExtra::row_spec(kableExtra::row_spec(knitr::kable(sched_df, format = "html", escape = FALSE), which(grepl("Midterm", sched_df$Subject)), bold = TRUE, background = "#F4B41A"), nrow(sched_df), bold = TRUE, background = "#E2725A")
```